name: awesome_dolar_price
description: "An App that looks up the dolar price in Venezuela"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flex_color_scheme: ^8.2.0
  flutter_hooks: ^0.21.2
  flutter_svg: ^2.2.0
  hooks_riverpod: ^3.0.0-dev.17
  riverpod_annotation: ^3.0.0-dev.17
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4
  flutter_layout_grid: ^2.0.8
  layout: ^1.0.5
  http: ^1.5.0
  html: ^0.15.6
  dart_date: ^1.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint: ^0.8.0
  build_runner: ^2.6.0
  riverpod_generator: ^3.0.0-dev.17
  riverpod_lint: ^3.0.0-dev.17

flutter:
  generate: true

  uses-material-design: true
  assets:
    - assets/icons/logo/logo.svg
    - assets/icons/logo/logo_extended.svg
    - assets/icons/logo/logo.png
    - assets/icons/logo/logo-extended.png
    - assets/icons/logo/logo-dark.png
    - assets/icons/logo/logo-extended-dark.png