name: doya
description: "An App that looks up the dolar price in Venezuela"
publish_to: 'none'
version: 1.2.0

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flex_color_scheme: ^8.2.0
  flutter_hooks: ^0.21.2
  flutter_svg: ^2.2.0
  hooks_riverpod: ^3.0.0-dev.17
  riverpod_annotation: ^3.0.0-dev.17
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4
  flutter_layout_grid: ^2.0.8
  layout: ^1.0.5
  dart_date: ^1.5.3
  currency_code_to_currency_symbol: ^0.0.4
  currency_text_input_formatter: ^2.3.0
  screenshot: ^3.0.0
  share_plus: ^11.1.0
  pasteboard: ^0.4.0
  google_fonts: ^6.3.0
  flutter_dotenv: ^6.0.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  dio: ^5.9.0
  package_info_plus: ^9.0.0
  device_info_plus: ^12.1.0
  url_launcher: ^6.3.2
  markdown: ^7.3.0
  flutter_html: ^3.0.0
  another_flushbar: ^1.12.32

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint: ^0.8.0
  build_runner: ^2.7.0
  riverpod_generator: ^3.0.0-dev.17
  riverpod_lint: ^3.0.0-dev.17
  freezed: ^3.2.3
  json_serializable: ^6.11.1

flutter:
  generate: true
  default-flavor: github

  uses-material-design: true
  assets:
    - assets/icons/logo/logo.png
    - assets/icons/logo/logo-256x256.png

    - assets/icons/logo/logo-branding.png
    - assets/icons/logo/logo-branding-512x512.png
    - assets/icons/logo/logo-branding-dark.png
    - assets/icons/logo/logo-branding-dark-512x512.png
    - assets/icons/logo/logo-title-with-slogan.png
    - assets/icons/logo/logo-title-with-slogan-dark.png
    - assets/icons/logo/logo-title.png

    - .env